{% set version = "0.2.9" %}

package:
  name: easyprocess
  version: {{ version }}

source:
  fn: easyprocess-{{ version }}.tar.gz
  url:  https://github.com/ponty/EasyProcess/archive/{{version}}.tar.gz
  sha256: 35e665905ccc4f604e7adb7fc95b6c11440e9161800a8e094ab3fa8424b3f3f6

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    

test:
  imports:
    - easyprocess

about:
  home: https://github.com/ponty/EasyProcess
  license: BSD 2-clause 
  license_file: LICENSE.txt
  summary: 'Easy to use python subprocess interface'

extra:
  recipe-maintainers:
    - ReimarBauer
