travis:
  secure:
    BINSTAR_TOKEN: LDrC4DWWKN33WyZLhpkguEQw1s0wRfAuI2DkU8yQUSikemdU5A4X5VpjTnFC829OzTXa7jJCbhmDOIP6EWBtilR+Gp9sUTHUA7gsy6St67hdxDfE1CmBQypQrG6PGW3kCRd7Pw/NwPKDy4T/7/UZ3J2EQ39nf1L8w4MHYaNQETIRVPBaadxmBn2nQau+DK8S0bEQdefzgknnXqhPxaXdj7P7YaMFF9r2znKDBsQEXPw9Okotgilv76em+WTXqOWuxgcrXTJxo+GbfxCY3EJFFtnT1I1OO2YGPqXI5i8E54t34M+RHMdzaD5tQDT5tYJ3U4aPAHzW8jf0LK//4g4UJUYGrU571RGWg2t4YSXD4osH3j/+KYl771NJhNn/p0qUBn94kPmoRiXrYjyEIKKW4yLXpGvJyLbWTeOHadlvD1NN5GuDKC/I89Q6lfzZ5+GpywZh6uaDdJIViClvuIIgLta05ssUNqhKFXwK0c0yt/SIAc+/Uu1rQBypIEQ/SBq4tNlNghZNGe1yKAgz3kU9jYUZ5Ugzcf7pxS5Yn+dWqE8ghCszn1zUhHgNz38NvJL22mQbeSjFvHYtPI0kbUZIwA4RB27dlHgLqNHdNkMj2iRJW4PDu9zDWmq5hTBvS54EuQOLBdxr2siCKKl+z4+qjodxQbB00ch2gSwAfcPqAK0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
