travis:
  secure:
    BINSTAR_TOKEN: r3aqlZ65SqQtD2E8sl4PWxbIuPG7dO3WE/rXjVTz3wv6UJT1pTos5k0N5loxqv3ufhcpV3F5VRt43+5ffAjEXVIYiOTkUuRhdeoNbXkuevb96Uo9scQgcb5BwgO9n5ullZ5coEOmNA3lESxj7DISK+8bga+ODZsHIeA7xjtEY4Bhvt2Ya22KhuMvTp12Ufy7Ux2PvYYbAokEWYLUlAbtHC6dM6N2QH9vp34PY455Xn+h3Y+tPZcoakhKhu6iS5HDzrEHdYimHHnpgQhcgnH7KeRHYIHy1CTPOCYUE9zg+YhnfdvwCwOP1vJqouebJLYLNheDz+QrJ+eIYlx+IKo8EpCqJa15+yVIZpRaSAHJDHR+dKaREQ+i1Arzd/ZiaXR80ycxWB0S1fDEp1Di0M3QsKDP2fXfLOl0tESK+JCr4NVPBCVvJLAc2D7EWqdwksKnLOLjUsvRcu0aYEHMpJNNHTANBMWL7R5W4qb+3HEaCYgsD4eXQ/UwxBh2koxbI+yXvh51pjYwKEWtcWxkfdhIpvpM1vwpMQREhC+8a5XoaUX6fp+Pt+XU0bRjIgFkPSy5Yb4qY91Jd62et2FxcLmQa7neHYwqVo0vJ0zo1HdhqFp967jEdi/tPHD+oY4Q3zjwte5C3Jxl1WQx+VZQWGWEOOegUtRNd3m2JJ4pqKITCek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
